### ISSUE TITLE
As a user I can view a single product detail

### ISSUE THREAD

**Issue by alstonwhite** [Warp-Speeders-Grace-Shopper/WarpSpeeders_GraceShoppers#10]
- [x] Create GET route for single product with ProductId
- [x] Set up Redux store for single product detail
- [x] Create frontend React component to display single product detail
- [x] Create routes for single product component

**Comment by tymonaghan** [comment]
these tasks were complete (see PRs #11 and #12 ). We just have not styled the component. Do we want to leave this in-progress until it's styled, mark this as done and make a new task to style it, other?
