### ISSUE TITLE
As a user, I can add a product to my cart

### ISSUE THREAD

**Issue by alstonwhite** [Warp-Speeders-Grace-Shopper/WarpSpeeders_GraceShoppers#13]
- [x] Set up Redux store/reducer for cart (addCart action)
- [x] Implement add to cart functionality to button on PDP
- [ ] Create route for cart component
- [ ] Create React component to display cart
- [ ] Create React component to display cart product tile
- [ ] Add cart button (router Link) to Nav bar

**Comment by tymonaghan** [comment]
We went ahead and merged this one in. I added the incomplete part (new functioning View Cart component) to a new issue #37
