### ISSUE TITLE
As a user, I can edit my cart

### ISSUE THREAD

**Issue by alstonwhite** [Warp-Speeders-Grace-Shopper/WarpSpeeders_GraceShoppers#14]
- [ ] Add editCartItem to cart reduce
- [x] Add deleteCartItem to cart reduce
- [ ] Implement edit cart functionality cart item tile (cart page)
- [x] Implement delete cart functionality cart item tile (cart page)

**Comment by tymonaghan** [comment]
We still need the ability to edit item quantities in the cart.

**Comment by tymonaghan** [comment]
closed by PR #69
