### ISSUE TITLE
EditProduct component warning

### ISSUE THREAD

**Issue by Slatteryr** [Warp-Speeders-Grace-Shopper/WarpSpeeders_GraceShoppers#43]
Warning: A component is changing a controlled input of type undefined to be uncontrolled.

**Comment by tymonaghan** [comment]
i believe https://github.com/Warp-Speeders-Grace-Shopper/WarpSpeeders_GraceShoppers/pull/58 took care of this one - confirm and close?

**Comment by tymonaghan** [comment]
closed by #58
